---
env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - airbnb
  - airbnb-typescript
  - prettier
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
  - sort-keys-fix
  - sort-destructure-keys
  - typescript-sort-keys
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    parserOptions:
      project:
        - './tsconfig.eslint.json'
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/no-extraneous-dependencies:
    'off'
    # - error
    # - devDependencies:
    #     - '**/*.test.ts'
    #     - '**/*.test.tsx'
    #     - targets/**
  import/prefer-default-export: 'off'
  import/order:
    - 'error'
    - alphabetize:
        caseInsensitive: true
        order: asc
      groups:
        - [builtin, external]
        - parent
        - sibling
        - index
        - object
      newlines-between: always
  react/jsx-sort-props: ['error', { reservedFirst: true }]
  react/no-unescaped-entities: ['error', { forbid: ['>', '}'] }]
  sort-destructure-keys/sort-destructure-keys: 'error'
  sort-imports:
    - 'error'
    - { ignoreCase: true, ignoreDeclarationSort: true }
  sort-keys-fix/sort-keys-fix: 'error'
  space-before-function-paren: 'off'
  typescript-sort-keys/interface: 'error'
  typescript-sort-keys/string-enum: 'error'
  '@typescript-eslint/no-unused-expressions': 'off'
  prettier/prettier: error
  arrow-body-style: 'off'
  prefer-arrow-callback: 'off'
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  react/require-default-props:
    - error
    - functions: defaultArguments
  react/jsx-props-no-spreading: 'off'
  no-nested-ternary: 'off'
  no-restricted-syntax: 'off'
  no-await-in-loop: 'off'
  no-console:
    - 'warn'
    - allow: ['warn', 'error', 'info', 'debug']
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: ./tsconfig.eslint.json
