version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./src:/opt/app/src:rw
      - ./config:/opt/app/config:rw
      - ./package.json:/opt/app/package.json:ro
    command: ['tsx', 'server']
    environment:
      NODE_ENV: development
      PORT: 80
