version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8002
    volumes:
      - ./src:/opt/app/src:rw
      - ./config:/opt/app/config:rw
      - ./package.json:/opt/app/package.json:ro
    command: ['tsx', 'server']
    environment:
      NODE_ENV: development
    links:
      - db
  db:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - db:/data/db:rw
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: test
    #   MONGO_INITDB_ROOT_PASSWORD: testPass

volumes:
  db:
    name: db
