name: CI Build
on:
  push:
    branches:
      - master
      - vite-typescript
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: ./bs docker --buildNum=$GITHUB_RUN_NUMBER
      - name: Publish docker image
        run: ./bs dockerPush
        env:
          DOCKER_USER: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      # - name: Docker deploy via SSH
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.DEPLOY_HOST }}
      #     username: ${{ secrets.DEPLOY_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: ${{ secrets.DEPLOY_PORT }}
      #     script: |
      #       docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      #       cd ${{ secrets.DEPLOY_DIR }}
      #       docker-compose pull
      #       docker-compose up -d
